# Generated by Django 4.2.7 on 2025-11-30 23:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Símbolo del gen (ej: BRCA1, TP53)', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Nombre completo del gen', max_length=255)),
                ('function_summary', models.TextField(help_text='Resumen de la función del gen en oncología')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gen de Interés',
                'verbose_name_plural': 'Genes de Interés',
                'db_table': 'genes',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(help_text='Cromosoma (ej: chr17, chrX)', max_length=10)),
                ('position', models.PositiveIntegerField(help_text='Posición en el cromosoma')),
                ('reference_base', models.CharField(help_text='Base(s) de referencia (ej: A, ATG)', max_length=100)),
                ('alternate_base', models.CharField(help_text='Base(s) alternativa(s) (ej: G, T)', max_length=100)),
                ('impact', models.CharField(choices=[('MISSENSE', 'Missense'), ('NONSENSE', 'Nonsense'), ('FRAMESHIFT', 'Frameshift'), ('SILENT', 'Silent'), ('SPLICE_SITE', 'Splice Site'), ('INFRAME_INSERTION', 'Inframe Insertion'), ('INFRAME_DELETION', 'Inframe Deletion'), ('OTHER', 'Other')], help_text='Tipo de impacto de la mutación', max_length=50)),
                ('clinical_significance', models.TextField(blank=True, help_text='Significancia clínica de la variante', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene', models.ForeignKey(help_text='Gen asociado a esta variante', on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='genomics.gene')),
            ],
            options={
                'verbose_name': 'Variante Genética',
                'verbose_name_plural': 'Variantes Genéticas',
                'db_table': 'genetic_variants',
                'ordering': ['chromosome', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(help_text='ID del paciente (consultable en Microservicio Clínica)')),
                ('detection_date', models.DateField(help_text='Fecha de detección de la variante')),
                ('allele_frequency', models.DecimalField(decimal_places=4, help_text='Frecuencia alélica (VAF - Variant Allele Frequency), valor entre 0 y 1', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sample_type', models.CharField(blank=True, help_text='Tipo de muestra (ej: sangre, tejido tumoral)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el reporte', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(help_text='Variante genética detectada', on_delete=django.db.models.deletion.PROTECT, related_name='patient_reports', to='genomics.geneticvariant')),
            ],
            options={
                'verbose_name': 'Reporte de Variante del Paciente',
                'verbose_name_plural': 'Reportes de Variantes de Pacientes',
                'db_table': 'patient_variant_reports',
                'ordering': ['-detection_date'],
                'indexes': [models.Index(fields=['patient_id'], name='patient_var_patient_c94b06_idx'), models.Index(fields=['detection_date'], name='patient_var_detecti_3b46bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='geneticvariant',
            index=models.Index(fields=['chromosome', 'position'], name='genetic_var_chromos_30c680_idx'),
        ),
        migrations.AddIndex(
            model_name='geneticvariant',
            index=models.Index(fields=['gene'], name='genetic_var_gene_id_1ed690_idx'),
        ),
    ]
